<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Defines the pxlraffle platform admin menu path.
 */
define('PXLRAFFLE_ADMIN_MENU_PATH', 'admin/pxlraffle');



//
// Adapts user profile form to support raffles
require_once 'includes/user.profile.inc';

//
// Adds user public functions
require_once 'includes/user.public.inc';

//
// Adds raffle public functions
require_once 'includes/raffle.public.inc';



/* --------------------------------------------------
 * PxlRaffle session data
 * --------------------------------------------------*/
/**
 * Session wide data container.
 *
 * @return array Returns the session data array.
 */
function &pxlraffle_session_data() {
  if (!isset($_SESSION['pxlRaffle'])) {
    $_SESSION['pxlRaffle'] = array();
  }
  return $_SESSION['pxlRaffle'];
}


/* --------------------------------------------------
 * PxlRaffle hook implementations
 * --------------------------------------------------*/

/**
 * Implements hook_permission().
 */
function pxlraffle_permission() {
  return array(
    'administer pixel raffle' => array(
      'title' => t('Administer PxlRaffle'),
      'description' => t('Allows to administer the settings for the Pixel Raffle module.'),
    ),
  );
}

/**
 * Define the pxlRaffle menu as top node of the admin menu.
 * All administration of the PxlRaffle platform is added below this menu.
 * @return mixed
 */
function pxlraffle_menu() {
  $items[PXLRAFFLE_ADMIN_MENU_PATH] = array(
    'title' => 'Pixel Raffle',
    'description' => 'PxlRaffle - a tool to collect and raffle money.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer pixel raffle'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -7,
  );

  //
  // pxlraffle admin forms
  $items[PXLRAFFLE_ADMIN_MENU_PATH . '/donations'] = array(
    'title' => 'Stripe donations',
    'description' => 'View all stripe donation payments.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pxlraffle_donation_overview'),
    'access arguments' => array('administer pixel raffle'),
    'file' => 'pxlraffle.admin.inc',
    'weight' => 0,
  );
  // callback: manage the current raffle for specified user
  $items['user/%pxlraffle_uid/raffle/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => '_pxlraffle_manage_user_raffle_callback',
    'page arguments' => array(1,3),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
  );
  return $items;
}

/**
 * User object auto loader.
 */
function pxlraffle_uid_load($uid) {
  if (is_array($uid)) {
    return array_values($uid)[0];
  }
  else {
    return user_load($uid);
  }
}


/**
 * This hook is called when the recurring payment subscription for the user is
 * successfully finished.
 * @param $user
 */
function pxlraffle_stripe_button_user_subscribed($user) {
  // update user after subscription
  pxlraffle_subscribe_user($user, true);
}

/**
 * This hook is called after the recurring payment subscription (Stripe) of the user has been deleted.
 * @param $user
 */
function pxlraffle_stripe_button_user_unsubscribed($user) {
  // update user after subscription deletion
  user_save($user, array('field_current_raffle' => null, 'field_raffle_code' => null));
}

/**
 * Hook called after the stripe charge transaction has been successfully performed.
 *
 * Used to update the current raffle with the donated money and update raffle state if needed.
 **/
function pxlraffle_stripe_button_charge_completed($charge_params) {
  //
  // update current raffle with the donated amount
  $rest_amount = pxlraffle_update_current_raffle_amount($charge_params);

  //
  // create new raffle, if rest amount is available
  if ($rest_amount) {
    pxlraffle_new_raffle($rest_amount);
  }
}


/* --------------------------------------------------
 * PxlRaffle menu callbacks
 * --------------------------------------------------*/

function _pxlraffle_manage_user_raffle_callback ($user, $action) {
  //
  // manage raffle on user
  switch ($action) {
    case 'renew':
      // update user raffle, if possible
      pxlraffle_renew_user_raffle($user);

      // redirect to participate page
      drupal_goto('/participate/#panel-participate', array(), 307);
      break;

    case 'renew-in-profile':
      // update user raffle, if possible
      pxlraffle_renew_user_raffle($user);

      // redirect to user edit form
      drupal_goto('user/' . $user->uid . '/edit', array(), 307);
      break;

    case 'remove':
      // remove user from raffle, if any
      if (!empty($user->field_current_raffle)) {
        $user = user_save($user, array('field_current_raffle' => null, 'field_raffle_code' => null));
        $msg = t('You (@user) have been successfully removed from any raffle.', array('@user' => $user->name));
        drupal_set_message($msg);
      }

      // redirect to participate page
      drupal_goto('/participate/#panel-participate', array(), 307);
      break;

    case 'remove-in-profile':
      // remove user from raffle, if any
      if (!empty($user->field_current_raffle)) {
        $user = user_save($user, array('field_current_raffle' => null, 'field_raffle_code' => null));
        $msg = t('You (@user) have been successfully removed from any raffle.', array('@user' => $user->name));
        drupal_set_message($msg);
      }

      // redirect to user edit form
      drupal_goto('user/' . $user->uid . '/edit', array(), 307);
      break;
  }

}



/* --------------------------------------------------
 * PxlRaffle themes
 * --------------------------------------------------*/

/**
 * Implements hook_theme().
 */
function pxlraffle_theme() {
  return array(
    'pxlraffle_fundraising' => array(
      'variables' => array(
        'container_id' => 'pxlraffle-fundraising',
      ),
      'file' => 'templates/pxlraffle_fundraising.vars.php',
      'template' => 'templates/pxlraffle_fundraising',
    ),
    'pxlraffle_next_raffle' => array(
      'variables' => array(
        'container_id' => 'pxlraffle-next-raffle',
      ),
      'file' => 'templates/pxlraffle_next_raffle.vars.php',
      'template' => 'templates/pxlraffle_next_raffle',
    ),
    'pxlraffle_subscriptions' => array(
      'variables' => array(
        'container_id' => 'pxlraffle-subscriptions',
      ),
      'file' => 'templates/pxlraffle_subscriptions.vars.php',
      'template' => 'templates/pxlraffle_subscriptions',
    ),
    'pxlraffle_participate' => array(
      'variables' => array(
        'container_id' => 'pxlraffle-participate',
      ),
      'file' => 'templates/pxlraffle_participate.vars.php',
      'template' => 'templates/pxlraffle_participate',
    ),
  );
}

function _pxlraffle_odometer_theme_attachments (&$vars, $delta) {
  // set variables
  $vars['odometer_label_on_top'] = variable_get($delta . '_odometer_label_position') == 'top';
  $vars['odometer_label'] = t(variable_get($delta . '_odometer_label'));

  // add js and css files
  $path = drupal_get_path('module', 'pxlraffle');
  $animated_range = variable_get($delta . '_odometer_anim_number_range');
  $format = variable_get($delta . '_odometer_format');
  $theme = variable_get($delta . '_odometer_theme');
  $css_file = $path;

  switch ($theme) {
    case 'car':
      $css_file .= '/css/odometer-theme-car.css';
      break;
    case 'train_station':
      $css_file .= '/css/odometer-theme-train-station.css';
      break;
    case 'digital':
      $css_file .= '/css/odometer-theme-digital.css';
      break;
    case 'minimal':
      $css_file .= '/css/odometer-theme-minimal.css';
      break;
    case 'plaza':
      $css_file .= '/css/odometer-theme-plaza.css';
      break;
    case 'slot_machine':
      $css_file .= '/css/odometer-theme-slot_machine.css';
      break;
    case 'default':
    default:
      $css_file .= '/css/odometer-theme-default.css';
      break;
  }

  // set js settings
  $js_settings = array(
    'pxlraffle_odometer' => array(
      'animated_range' => $animated_range,
      'format' => $format,
    ),
  );

  // add files
  drupal_add_css($css_file);
  drupal_add_js($path . '/js/odometer.min.js');
  drupal_add_js($path . '/js/odometer_anim.js');
  drupal_add_js($js_settings, 'setting');

}


/* --------------------------------------------------
 * PxlRaffle blocks
 * --------------------------------------------------*/
/**
 * Implements hook_block_info().
 */
function pxlraffle_block_info() {
  $blocks['pxlraffle_fundraising'] = array(
    'info' => t('Raffle: Current fundraising information'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['pxlraffle_next_raffle'] = array(
    'info' => t('Raffle: Next drawing'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['pxlraffle_subscriptions'] = array(
    'info' => t('Raffle: Current subscription information'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['pxlraffle_participate'] = array(
    'info' => t('Raffle: Login and user information'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function pxlraffle_block_configure($delta = '') {
  switch ($delta) {
    case 'pxlraffle_fundraising':
    case 'pxlraffle_subscriptions':
      return _pxlraffle_odometer_settings_form($delta);
  }
}


function _pxlraffle_odometer_settings_form ($delta) {
  $form['pxlraffle_odometer'] = array(
    '#type'         => 'fieldset',
    '#title'        => t('Odometer specific configuration'),
    '#description'   => t('Configure the odometer specific values.'),
    '#collapsible'  => FALSE,
    '#collapsed'    => FALSE,
  );
  $form['pxlraffle_odometer']['pxlraffle_odometer_label'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Odometer label'),
    '#default_value' => variable_get($delta . '_odometer_label', ''),
    '#description'   => t('Sets the label for the odometer'),
  );
  $form['pxlraffle_odometer']['pxlraffle_odometer_label_position'] = array(
    '#type' => 'radios',
    '#title' => t('Position of label'),
    '#default_value' => variable_get($delta . '_odometer_label_position', 'top'),
    '#options' => array(
      'top' => t('Label above odometer'),
      'bottom' => t('Label below odometer'),
    ),
  );
  $form['pxlraffle_odometer']['pxlraffle_odometer_anim_number_range'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Animated number range'),
    '#default_value' => variable_get($delta . '_odometer_anim_number_range', 0),
    '#description'   => t('Define the range of numbers that are animated when the odometer is shown.'),
  );
  $form['pxlraffle_odometer']['pxlraffle_odometer_format'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Number format'),
    '#default_value' => variable_get($delta . '_odometer_format', "('ddd).dd"),
    '#description'   => t("Define the format of the displayed number. Default: ('ddd).dd."),
  );
  $form['pxlraffle_odometer']['pxlraffle_odometer_theme'] = array(
    '#type' => 'select',
    '#title' => t('Theme'),
    '#options' => array(
      'default' => t('Default'),
      'car' => t('Car'),
      'train_station' => t('Train station'),
      'digital' => t('Digital'),
      'minimal' => t('Minimal'),
      'plaza' => t('Plaza'),
      'slot_machine' => t('Slot machine'),
    ),
    '#description' => t('Select a predefined theme. All themes can be customized in CSS.'),
    '#default_value' => variable_get($delta . '_odometer_theme', 'default'),
  );

  return $form;
}

/**
 * Implements hook_block_save().
 */
function pxlraffle_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'pxlraffle_fundraising':
    case 'pxlraffle_subscriptions':
      variable_set($delta . '_odometer_label', $edit['pxlraffle_odometer_label']);
      variable_set($delta . '_odometer_label_position', $edit['pxlraffle_odometer_label_position']);
      variable_set($delta . '_odometer_anim_number_range', $edit['pxlraffle_odometer_anim_number_range']);
      variable_set($delta . '_odometer_format', $edit['pxlraffle_odometer_format']);
      variable_set($delta . '_odometer_theme', $edit['pxlraffle_odometer_theme']);
      break;
  }
}


/**
 * Implements hook_block_view().
 *
 * Displays the current raffle information.
 */
function pxlraffle_block_view($delta = 0) {
  $block = array();

  switch ($delta) {
    case 'pxlraffle_fundraising':
      $block['subject'] = null;
      $block['content'] = theme('pxlraffle_fundraising');
      break;
    case 'pxlraffle_next_raffle':
      $block['subject'] = null;
      $block['content'] = theme('pxlraffle_next_raffle');
      break;
    case 'pxlraffle_subscriptions':
      $block['subject'] = null;
      $block['content'] = theme('pxlraffle_subscriptions');
      break;
    case 'pxlraffle_participate':
      $block['subject'] = null;
      $block['content'] = theme('pxlraffle_participate');
      break;
  }
  return $block;
}

